### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by Wakata-Masaya** [ChengBinJin/MRI-to-CT-DCNN-TensorFlow#1]
hello.
i have two questions.
first, how did you get dataset?
second, how did you convert images into 8bit - .png data?

**Comment by ChengBinJin** [comment]
@Wakata-Masaya The dataset used in my repository is the public toy dataset for education. However, I'm sorry, I forget the address of dataset. To save as .png file, I normalized the original 16bit data by finding the minimum and maximum for each case data to 0~255 uint8 type. However, I highly recommend using the original data in research.

**Comment by Wakata-Masaya** [comment]
thank you.
i try to find original data.

**Comment by happyqianwei** [comment]
Hi @ChengBinJin @Wakata-Masaya, have you found the original dataset of paired CT and MR data? I'm interested in your work @ChengBinJin. Is your model able to process 3D images directly or I have to slice it into 2D images as the input to the network? Thanks!

**Comment by ChengBinJin** [comment]
@happyqianwei I didn't try it on the 3D data. But, I think after revising the three aspects, it will work. Firstly, you need to write your customized 3d_data_reader function. Then, all of the 2d convolution layers should be replaced by Conv3D. The last one may be that you need to consider patch-based 3D input. Because I'm afraid, the memory of the GPU is not enough to handle the whole image.

**Comment by happyqianwei** [comment]
Make sense! Thanks a lot for your advice @ChengBinJin The key challenge for us is the lack of paired CT and MRI to trained the model. Have you trained a model based on real paired dataset? Is it possible to share the model for academic usage? Our purpose is to see bone morphology from the synthesized CT as only MRI are available. Look forward to hearing from you.

**Comment by ChengBinJin** [comment]
@happyqianwei Yes, we have the experience using the real paired dataset. Our team has another researcher focus on data alignment using 3dAlleniate function from AFNI (Analysis of Functional NeuroImages) library. In order to do data alignment, we need the raw Dicom file to get the position and other information. And this code is available for academic work.

**Comment by happyqianwei** [comment]
Thanks @ChengBinJin for your useful information about image registration. We will use it for MR and CT data alignment. However, it's a pity that we don't have paired MR-CT images and we wonder is it possible for you to share with us the model that estimates CT from MR? or do you have source code available to train unpaired data? Very much appreciate it.

**Comment by ChengBinJin** [comment]
@happyqianwei Sure, you can download our model from the following link: https://www.dropbox.com/s/yxq3nre0zloykn0/model.zip?dl=0. 
However, we found that the model is highly depended on the training data. Each scanning device from the different manufacture has the various magnitude of the intensity. Therefore, developing a general estimation model for the multiple devices of different manufacturers is an open problem. 

For the model using the unpaired data, you can refer our another repository [SpineC2M](https://github.com/ChengBinJin/SpineC2M). In this repository, we also implemented a reference method named [Deep MR to CT](https://link.springer.com/chapter/10.1007/978-3-319-68127-6_2). You can try this model if you have unpaired data only.

**Comment by happyqianwei** [comment]
@ChengBinJin Very much appreciate it! Thanks for sharing the model and the code:) Very helpful. You've done fruitful work in the area. We're very interested in trying them and would like to communicate with you along the way. Please don't mind if I have further questions.

**Comment by jesuis76** [comment]
Hello^^ I have a problem about path. When I ran the code, "main.ipynb" on Jupyter lab, I met an error like 'FileNotFoundError: [WinError3] ../../Data\\brain01\\post'. Since python on Win10 works when I used / or \\ for a path representation, I thought it won't be a cause. However, I can not find what cause is for this error. Additionally, "post" folder did not come up under the brain01 folder. I would like to ask your advice to fix this problem. Thank you for your time.

**Comment by ChengBinJin** [comment]
@happyqianwei  My pleasure. Any comments, questions, and discussions are welcome!

**Comment by ChengBinJin** [comment]
@jesuis76 
I think you didn't run the data pre-processing step, did you? We need this process for N4 Bias Correction, Histogram Matching, Masking out, and Mask generation. So please run `python preprocessing.py --delay=1 --is_save` first. Then, a file named post will be created, and all of the processed images will be saved in this file.
